[package]
org = "fooddelivery"
name = "admin_service"
version = "1.0.0"
distribution = "2201.9.0"

[[platform.java17.dependency]]
groupId = "org.mongodb"
artifactId = "mongodb-driver-sync"
version = "4.11.1"

[[platform.java17.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "3.6.0"

[build-options]
observabilityIncluded = true